import { useEffect, useRef, useState, type CSSProperties } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowUpRight, Mail, MapPin, Menu, X, Sparkles, Search, Sun, Moon } from 'lucide-react'
import './styles.css'
import './process.css'
import './happy.css'

type Link = { label: string; href: string; placeholder?: boolean }
type Project = { number: string; title: string; description: string; tags: string[]; metric: string; metricLabel: string; links: Link[]; color: 'lime' | 'coral' | 'blue'; image?: string; award?: string; featured?: boolean }
type Experience = { company: string; role: string; dates: string; location: string; bullets: string[] }
type Leadership = { organization: string; role: string; dates: string; bullets: string[] }

const links = { linkedin: 'https://ca.linkedin.com/in/melvika', devpost: 'https://devpost.com/melvikafa', github: 'https://github.com/melvikaf', email: 'mailto:melvikafaustine@gmail.com' }

const projects: Project[] = [
  { number: '01', title: 'CrimePath', description: 'A full-stack investigative timeline prototype connecting cases, evidence, witnesses, events, and victims through a traceable temporal data model.', tags: ['PostgreSQL', 'TimescaleDB', 'TypeScript', 'React'], metric: 'StormHacks', metricLabel: 'Best Use of Gemini API - MLH', color: 'lime', image: 'https://d112y698adiu2z.cloudfront.net/photos/production/software_thumbnail_photos/005/511/936/datas/medium.png', award: 'Best Use of Gemini API - MLH', featured: true, links: [{ label: 'Devpost', href: 'https://devpost.com/software/crimepath' }, { label: 'GitHub', href: links.github, placeholder: true }] },
  { number: '02', title: 'Love Signal', description: 'A proximity-based social discovery application combining profile, location, private signals, mutual matches, and map-based discovery.', tags: ['React', 'TypeScript', 'MongoDB', 'Vercel'], metric: 'cmd-f', metricLabel: '2026 build', color: 'coral', image: 'https://d112y698adiu2z.cloudfront.net/photos/production/software_thumbnail_photos/004/413/711/datas/medium.png', featured: true, links: [{ label: 'Devpost', href: 'https://devpost.com/software/love-signal' }, { label: 'GitHub', href: links.github, placeholder: true }] },
  { number: '03', title: 'Shaka - Air DJ', description: 'A touch-free music control system translating webcam hand movements into real-time audio commands through a WebSocket pipeline.', tags: ['MediaPipe', 'OpenCV', 'WebSockets', 'React'], metric: 'StormHacks', metricLabel: '2025 build', color: 'lime', featured: true, links: [{ label: 'Devpost', href: 'https://devpost.com/software/shaka-air-dj' }, { label: 'GitHub', href: links.github, placeholder: true }] },
  { number: '04', title: 'Remy', description: 'A sleep-focused mobile app combining sleep analytics, personalized music, and accessible visualizations backed by Firebase.', tags: ['React Native', 'Firebase', 'HealthKit'], metric: 'DreamHacks', metricLabel: '2025 project', color: 'blue', image: 'https://d112y698adiu2z.cloudfront.net/photos/production/software_photos/003/320/261/datas/medium.jpeg', featured: true, links: [{ label: 'Devpost', href: 'https://devpost.com/software/remy-ie97ts' }, { label: 'GitHub', href: links.github, placeholder: true }] },
  { number: '05', title: 'ParkAble', description: 'A mobile parking availability experience using YOLO and OpenCV to detect occupancy from camera footage and serve status through REST APIs.', tags: ['React Native', 'YOLO', 'OpenCV', 'MongoDB'], metric: 'cmd-f', metricLabel: '2025 build', color: 'coral', links: [{ label: 'Devpost', href: 'https://devpost.com/software/spotable' }, { label: 'GitHub', href: links.github, placeholder: true }] },
  { number: '06', title: 'CareConnect', description: 'A wellbeing web application combining individual check-ins with aggregate team analytics, real-time Firebase updates, and Recharts visualizations.', tags: ['React', 'Firebase', 'Recharts', 'Tailwind'], metric: 'StormHacks', metricLabel: '2024 build', color: 'blue', links: [{ label: 'Devpost', href: 'https://devpost.com/software/careconnect-eand43' }, { label: 'GitHub', href: links.github, placeholder: true }] },
  { number: '07', title: 'FIFA World Cup Predictor', description: 'An end-to-end machine learning pipeline that turns historical international football data into match predictions and tournament-level outcomes.', tags: ['Python', 'pandas', 'scikit-learn', 'Jupyter'], metric: 'ML', metricLabel: 'prediction pipeline', color: 'coral', links: [{ label: 'GitHub', href: links.github, placeholder: true }] },
  { number: '08', title: 'Problematic Internet Use Prediction', description: 'A data science workflow for cleaning behavioural and demographic observations, engineering features, and evaluating candidate predictive models.', tags: ['Python', 'pandas', 'scikit-learn'], metric: 'DS', metricLabel: 'model study', color: 'blue', links: [{ label: 'GitHub', href: links.github, placeholder: true }] },
]

const experience: Experience[] = [
  { company: 'Waterworth', role: 'Junior Data Analyst Co-op', dates: 'May 2026 - Sep. 2026', location: 'Victoria, BC', bullets: ['Delivered trusted ARR, NRR, and GRR reporting through reusable PostgreSQL, Python, Power Query, and Excel workflows.', 'Built a Python Dash simulator for scenario-based capacity and staffing analysis.', 'Connected HubSpot, PostgreSQL, Python, and Excel data into repeatable analytical workflows.'] },
  { company: 'Vancouver Coastal Health', role: 'Data Analytics / Data Science Intern', dates: 'Jan. 2026 - Apr. 2026', location: 'Vancouver, BC', bullets: ['Improved usability of healthcare datasets spanning more than 3M records through Python and Azure Databricks workflows.', 'Automated QA workflows for Checkbox and REDCap, validating field mappings, branching logic, and production data flows.', 'Translated healthcare requirements into reproducible validation rules and documented workflows.'] },
  { company: 'Nettwerk Music Group', role: 'Data Insights Analyst Co-op Student', dates: 'Sep. 2025 - Jan. 2026', location: 'Vancouver, BC', bullets: ['Simplified analysis across more than 190M records with Snowflake SQL for downstream Tableau reporting.', 'Unified four Tableau dashboards into a consolidated analytical view across artist, audience, and engagement reporting.', 'Developed reusable Tableau views and standardized outputs across more than 200 artists.'] },
]

const education = [
  { school: 'Simon Fraser University', program: 'Bachelor of Science, Data Science', dates: 'Expected 2027', detail: 'Building a foundation across statistics, computing, machine learning, and the social context around data.' },
  { school: 'Langara College', program: 'Transfer studies', dates: '2022 - 2024', detail: 'Started my post-secondary journey before transferring to SFU.' },
]

const leadership: Leadership[] = [
  { organization: 'Women in Data Science at SFU', role: 'Co-Founder and President', dates: '2026 - Present', bullets: ['Co-founded a student community for women and gender-diverse students interested in data science, analytics, machine learning, and responsible technology.', 'Set early direction for the organization, including community-building, professional development, and opportunities to learn with peers.', 'Help create a welcoming bridge between technical learning, career exploration, and the broader SFU data community.'] },
  { organization: 'SFU Blueprint', role: 'VP Internal (current) · Product Manager & Co-Project Manager · VP Operations · Event Coordinator', dates: 'May 2025 - Present', bullets: ['Progressed from Event Coordinator to VP Operations, Product Manager and Co-Project Manager, and now VP Internal.', 'Planned and supported events while coordinating logistics, people, timelines, and follow-through across the organization.', 'As Product Manager and Co-Project Manager, translated stakeholder needs into roadmaps, tickets, priorities, and delivery plans while contributing React and TypeScript frontend work.', 'As VP Internal, support organizational continuity, internal processes, member coordination, and a strong team culture.'] },
  { organization: 'SFU Marketing Association (SMA)', role: 'Marketing Project Coordinator', dates: 'Dec. 2025 - Apr. 2026', bullets: ['Supported marketing projects and student-facing initiatives within the SFU Marketing Association.', 'Coordinated project details, communication, and follow-through across collaborators and stakeholders.', 'Built experience at the intersection of audience understanding, clear communication, and organized execution.'] },
  { organization: 'Garuda Indonesian Langara Association (GILA)', role: 'Vice President & Co-Founder', dates: 'Aug. 2022 - Sep. 2023', bullets: ['Co-founded a Langara College student organization focused on building community for Indonesian students and peers.', 'Led planning, communications, and logistics for cultural initiatives, including Indonesian Game Day.', 'Managed member engagement and facilitated communication between executive leaders and general members.', 'Coordinated with external partners to secure venues and support event execution and campus outreach.'] },
]

const processSteps = [
  { number: '01', title: 'Understand the question', text: 'Before touching a dataset, I clarify the decision behind it: who needs to know what, why now, and what would a useful answer change?' },
  { number: '02', title: 'Explore the data', text: 'I look for shape, context, missingness, bias, and surprising relationships - using EDA to understand what the data can and cannot say.' },
  { number: '03', title: 'Transform with intent', text: 'I clean, validate, join, and model the data so the pipeline is reproducible and the definitions stay trustworthy from source to output.' },
  { number: '04', title: 'Engineer useful features', text: 'I translate domain knowledge into signals a model can use, while keeping the features interpretable enough to explain to the people who rely on them.' },
  { number: '05', title: 'Model the right way', text: 'I compare approaches against the real objective, measure what matters, and treat a model as a tool for a decision - not the finish line.' },
  { number: '06', title: 'Improve with feedback', text: 'I share the result, listen to how it works in practice, and iterate. The best data products get better because the people using them shape the next version.' },
]

const skills = ['Python', 'SQL', 'R', 'TypeScript', 'JavaScript', 'Java', 'C++', 'PostgreSQL', 'Snowflake', 'MySQL', 'MongoDB', 'TimescaleDB', 'pandas', 'scikit-learn', 'Power BI', 'Tableau', 'React', 'React Native', 'Flask', 'Node.js', 'REST APIs', 'WebSockets', 'Azure Databricks', 'Firebase', 'Git', 'Jupyter']

const interests = [
  { label: '01', title: 'Stories with a little tension', text: 'Historical romance films and books - especially Pride & Prejudice (2005), for the atmosphere, restraint, and the slow reveal of what people really mean.' },
  { label: '02', title: 'Cooking, eating, repeating', text: 'I love food in both directions: making something from whatever is in the kitchen, then happily planning my next meal while I eat the first one.' },
  { label: '03', title: 'Scent and small discoveries', text: 'I love perfumes, trying new things, and noticing the tiny details that make an experience feel personal - a note, a texture, a combination, a surprise.' },
  { label: '04', title: 'Always somewhere new', text: 'I have travelled to more than 10 countries, and I love how a new place changes what you notice - the food, the pace, the small systems that make daily life work.' },
]

function InterestCard({ interest }: { interest: (typeof interests)[number] }) {
  const [isOpen, setIsOpen] = useState(false)
  const toggle = () => setIsOpen(value => !value)
  return <article className={`interest-card postcard ${isOpen ? 'is-open' : ''}`} onClick={toggle} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); toggle() } }} role="button" tabIndex={0} aria-expanded={isOpen}>
    <div className="postcard-top"><span>{interest.label}</span><small>{isOpen ? 'close note' : 'click to unfold'} ↗</small></div>
    <h3>{interest.title}</h3>
    <p>{interest.text}</p>
    <span className="postcard-stamp">MF / from the margins</span>
  </article>
}

function ExternalLink({ link }: { link: Link }) { return <a className={link.placeholder ? 'project-link placeholder-link' : 'project-link'} href={link.placeholder ? '#' : link.href} onClick={(event) => link.placeholder && event.preventDefault()}>{link.label} <ArrowUpRight size={13} /></a> }

function ProjectCard({ project }: { project: Project }) {
  return <article className={`project-card ${project.color}`}><div className="project-number">{project.number}</div><div className="project-main">{project.image ? <img className="project-image" src={project.image} alt={`${project.title} project thumbnail`} /> : <div className="project-photo-placeholder"><span>PROJECT IMAGE</span><small>Add screenshot / photo</small></div>}{project.award && <p className="project-award">✦ {project.award}</p>}<h3>{project.title}</h3><p>{project.description}</p><div className="tag-row">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div><div className="project-links">{project.links.map(link => <ExternalLink key={link.label} link={link} />)}</div></div><div className="project-metric"><strong>{project.metric}</strong><span>{project.metricLabel}</span></div><a className="project-arrow" href={project.links[0]?.href || '#contact'} aria-label={`View ${project.title}`}><ArrowUpRight size={23} /></a></article>
}

function ProcessSection() {
  const sectionRef = useRef<HTMLElement>(null); const [progress, setProgress] = useState(0); const [activeStep, setActiveStep] = useState(0)
  useEffect(() => { const updatePath = () => { if (!sectionRef.current) return; const rect = sectionRef.current.getBoundingClientRect(); const travel = Math.max(rect.height - window.innerHeight, 1); const nextProgress = Math.min(1, Math.max(0, -rect.top / travel)); setProgress(nextProgress); setActiveStep(Math.min(processSteps.length - 1, Math.floor(nextProgress * processSteps.length))) }; updatePath(); window.addEventListener('scroll', updatePath, { passive: true }); window.addEventListener('resize', updatePath); return () => { window.removeEventListener('scroll', updatePath); window.removeEventListener('resize', updatePath) } }, [])
  return <section className="process-section" id="process" ref={sectionRef}><div className="process-sticky"><p className="eyebrow">How I work with data</p><h2>A path from<br /><em>question</em> to<br />confidence.</h2><p className="process-intro">Good analysis is a conversation between the question, the data, the model, and the people who use the result.</p><div className="process-progress"><span style={{ transform: `scaleY(${progress})` }} /><b>{String(activeStep + 1).padStart(2, '0')} / 06</b></div></div><div className="process-track" style={{ '--process-progress': progress } as CSSProperties}><div className="process-line" />{processSteps.map((step, index) => <article className={`process-step ${index <= activeStep ? 'is-active' : ''}`} key={step.number}><div className="process-node">{step.number}</div><div><p className="process-kicker">STAGE {step.number}</p><h3>{step.title}</h3><p>{step.text}</p></div></article>)}</div></section>
}

function App() {
  const [menuOpen, setMenuOpen] = useState(false); const [query, setQuery] = useState(''); const [theme, setTheme] = useState<'light' | 'dark'>(() => { if (typeof window === 'undefined') return 'light'; const saved = window.localStorage.getItem('portfolio-theme'); if (saved === 'dark' || saved === 'light') return saved; return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light' }); const closeMenu = () => setMenuOpen(false)
  useEffect(() => { const saved = window.localStorage.getItem('portfolio-theme'); if (saved) return; const preference = window.matchMedia('(prefers-color-scheme: dark)'); const updateFromBrowser = (event: MediaQueryListEvent) => setTheme(event.matches ? 'dark' : 'light'); preference.addEventListener('change', updateFromBrowser); return () => preference.removeEventListener('change', updateFromBrowser) }, [])
  const toggleTheme = () => { const nextTheme = theme === 'light' ? 'dark' : 'light'; setTheme(nextTheme); window.localStorage.setItem('portfolio-theme', nextTheme) }
  const selectedProjects = projects.filter(project => project.featured)
  const filteredProjects = projects.filter(project => `${project.title} ${project.description} ${project.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()))
  return <div className={`site-shell ${theme === 'dark' ? 'theme-dark' : ''}`}>
    <header className="nav-wrap"><a className="brand" href="#top" onClick={closeMenu} aria-label="Melvika Faustine home"><span className="brand-mark">MF</span><span>Melvika Faustine</span></a><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation" aria-expanded={menuOpen}>{menuOpen ? <X size={22} /> : <Menu size={22} />}</button><nav className={`nav-links ${menuOpen ? 'is-open' : ''}`}><a href="#process" onClick={closeMenu}>My process</a><a href="#work" onClick={closeMenu}>Selected work</a><a href="#all-projects" onClick={closeMenu}>All projects</a><a href="#experience" onClick={closeMenu}>Experience</a><a href="#contact" onClick={closeMenu}>Contact</a><button className="theme-toggle" onClick={toggleTheme} aria-label={`Switch to ${theme === 'light' ? 'dark' : 'light'} mode`} title={`Switch to ${theme === 'light' ? 'dark' : 'light'} mode`}>{theme === 'light' ? <Moon size={15} /> : <Sun size={15} />}<span>{theme === 'light' ? 'Dark mode' : 'Light mode'}</span></button></nav></header>
    <main id="top">
      <section className="hero section-grid"><div className="hero-copy"><p className="eyebrow"><span className="pulse-dot" /> Data science student - Burnaby, BC</p><h1>I turn messy<br /><em>questions</em> into<br /><span className="outline-text">clearer</span> decisions.</h1><p className="hero-intro">I am Melvika - a data science student graduating in 2027, with experience across healthcare, SaaS, music, and full-stack projects.</p><div className="hero-actions"><a className="button button-primary" href="#process">See how I think <ArrowUpRight size={17} /></a><a className="text-link" href={links.email}>Let&apos;s talk <span>↗</span></a></div></div><div className="hero-visual"><div className="visual-label">CURRENTLY EXPLORING <span>●</span></div><div className="portrait-placeholder"><div className="placeholder-frame"><span>MF</span></div><p>PHOTO PLACEHOLDER</p><small>Add a portrait or profile image here</small></div><div className="chart-card"><div className="chart-top"><span>attention / time</span><span>2024-25</span></div><div className="chart-area"><div className="chart-y"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><svg viewBox="0 0 420 220" preserveAspectRatio="none" role="img" aria-label="Rising line chart"><defs><linearGradient id="chartFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#d8f56a" stopOpacity=".35" /><stop offset="100%" stopColor="#d8f56a" stopOpacity="0" /></linearGradient></defs><path className="grid-line" d="M0 24H420M0 76H420M0 128H420M0 180H420" /><path className="chart-fill" d="M0 179 C38 173 39 143 74 152 S109 115 138 132 S164 81 193 102 S224 117 250 67 S282 52 306 81 S346 26 372 40 S401 22 420 10 V220 H0Z" /><path className="chart-line" d="M0 179 C38 173 39 143 74 152 S109 115 138 132 S164 81 193 102 S224 117 250 67 S282 52 306 81 S346 26 372 40 S401 22 420 10" /><circle cx="420" cy="10" r="5" fill="#d8f56a" /></svg></div><div className="chart-bottom"><span>oct</span><span>dec</span><span>feb</span><span>apr</span><span>jun</span></div></div><div className="visual-note"><Sparkles size={15} /> curiosity is a feature, not a bug</div></div></section>
      <section className="ticker" aria-label="Areas of interest"><span>STATISTICS</span><b>✳</b><span>STORYTELLING</span><b>✳</b><span>MACHINE LEARNING</span><b>✳</b><span>GOOD QUESTIONS</span><b>✳</b><span>STATISTICS</span></section>
      <ProcessSection />
      <section className="work-section" id="work"><div className="section-heading"><div><p className="eyebrow">A focused edit</p><h2>Selected <em>work</em></h2></div><p className="heading-note">The projects I would start with in a conversation.</p></div><div className="project-list">{selectedProjects.map(project => <ProjectCard key={project.number} project={project} />)}</div></section>
      <section className="all-projects-section" id="all-projects"><details className="project-archive"><summary><span><p className="eyebrow">The complete archive</p><h2>All <em>projects</em></h2></span><span className="archive-toggle">Browse all projects <ArrowUpRight size={18} /></span></summary><div className="archive-content"><p className="heading-note">Search by project, tool, or area of interest.</p><label className="project-search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search projects, tools, or technologies..." aria-label="Search all projects" /></label><p className="search-count">Showing {filteredProjects.length} of {projects.length} projects</p><div className="project-list">{filteredProjects.length ? filteredProjects.map(project => <ProjectCard key={project.number} project={project} />) : <div className="empty-projects">No projects match that search yet.</div>}</div></div></details></section>
      <section className="experience-section" id="experience"><div className="section-heading"><div><p className="eyebrow">Where I have learned</p><h2>Experience <em>with impact</em></h2></div><p className="heading-note">Three data-focused co-ops across healthcare, SaaS, and music.</p></div><div className="experience-list">{experience.map(item => <article className="experience-item" key={item.company}><div className="experience-meta"><span>{item.dates}</span><span>{item.location}</span></div><div><h3>{item.company}</h3><p className="experience-role">{item.role}</p><ul>{item.bullets.map(bullet => <li key={bullet}>{bullet}</li>)}</ul></div></article>)}</div></section>
      <section className="education-section"><div className="section-heading"><div><p className="eyebrow">The foundation</p><h2>Education <em>in progress</em></h2></div><p className="heading-note">The questions I ask in practice are grounded in statistics, computing, and curiosity.</p></div><div className="education-list">{education.map(item => <article className="education-item" key={item.school}><div className="education-meta"><span>{item.dates}</span></div><div><h3>{item.school}</h3><p className="experience-role">{item.program}</p><p>{item.detail}</p></div></article>)}</div></section>
      <section className="leadership-section"><div className="section-heading"><div><p className="eyebrow">Community and leadership</p><h2>People make<br /><em>the work</em> better.</h2></div><p className="heading-note">The spaces where I organize, contribute, and learn with others.</p></div><div className="leadership-list">{leadership.map(item => <article className="leadership-item" key={item.organization}><div className="leadership-meta"><span>{item.dates}</span></div><div><h3>{item.organization}</h3><p className="experience-role">{item.role}</p><ul>{item.bullets.map(bullet => <li key={bullet}>{bullet}</li>)}</ul></div></article>)}</div></section>
      <section className="interests-section"><div className="section-heading"><div><p className="eyebrow">Beyond the dataset</p><h2>The details I<br /><em>notice.</em></h2></div><p className="heading-note">The very human things that keep me curious: food, stories, travel, and scent.<br /><strong className="postcard-invite">Choose a postcard to unfold it ↗</strong></p></div><div className="interests-grid">{interests.map(interest => <InterestCard key={interest.label} interest={interest} />)}</div></section>
      <section className="about-section" id="about"><div className="about-intro"><p className="eyebrow">The short version</p><h2>Numbers are<br /><em>only half</em><br />the story.</h2></div><div className="about-content"><p className="lead">I am studying Data Science at Simon Fraser University because I am interested in the space between a dataset and a decision.</p><p>I like turning ambiguous questions into clean notebooks, reliable pipelines, clear dashboards, and tools that people can actually use. I am currently deepening my skills in causal inference, geospatial data, and thoughtful machine learning.</p><div className="skill-grid"><div className="skill"><span>01</span><h3>Find the signal</h3><p>Exploratory analysis, visual storytelling, and asking the useful second question.</p></div><div className="skill"><span>02</span><h3>Build with care</h3><p>Readable code, thoughtful models, and data products grounded in context.</p></div><div className="skill"><span>03</span><h3>Keep learning</h3><p>SFU Data Science - Expected 2027 - Langara College transfer studies.</p></div></div></div></section>
      <section className="skills-section"><div className="skills-heading"><p className="eyebrow">Technical toolkit</p><h2>Things I work <em>with</em></h2></div><div className="skills-cloud">{skills.map(skill => <span key={skill}>{skill}</span>)}</div></section>
      <section className="contact-section" id="contact"><div className="contact-inner"><p className="eyebrow">Have a question, project, or good dataset?</p><h2>Let&apos;s make<br /><em>something useful.</em></h2><a className="button button-primary" href="mailto:melvikafaustine@gmail.com">Say hello <Mail size={17} /></a><p className="contact-email">melvikafaustine@gmail.com</p><div className="contact-meta"><span><MapPin size={15} /> Burnaby, BC</span><a href={links.linkedin}>LinkedIn ↗</a><a href={links.devpost}>Devpost ↗</a><a href={links.github}>GitHub ↗</a></div></div></section>
    </main>
    <footer><span>© 2025 Melvika Faustine</span><span className="footer-note">built with curiosity + caffeine</span><div className="socials"><a href={links.github} aria-label="GitHub">GH</a><a href={links.linkedin} aria-label="LinkedIn">in</a><a href={links.email} aria-label="Email"><Mail size={18} /></a></div></footer>
  </div>
}

createRoot(document.getElementById('root')!).render(<App />)
